[package]
name = "hangman-server"
version = "0.1.0"
authors = ["J/A <archer884@gmail.com>"]

[dependencies]
# clippy = "*"
iron = "*"
persistent = "*"
rand = "*"
router = "*"
serde = "*"
serde_json = "*"
serde_macros = "*"